src/main/java/org/cejug/yougi/entity/Timezone.java
/* Yougi is a web application conceived to manage user groups or
 * communities focused on a certain domain of knowledge, whose members are
 * constantly sharing information and participating in social and educational
 * events. Copyright (C) 2011 Hildeberto Mendonça.
 *
 * This application is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation; either version 2.1 of the License, or (at your
 * option) any later version.
 *
 * This application is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * There is a full copy of the GNU Lesser General Public License along with
 * this library. Look for the file license.txt at the root level. If you do not
 * find it, write to the Free Software Foundation, Inc., 59 Temple Place,
 * Suite 330, Boston, MA 02111-1307 USA.
 * */
package org.cejug.yougi.entity;

import java.io.Serializable;
import java.util.TimeZone;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Due to the user-unfriendly Java TimeZone implementation, this class was
 * created to represent friendly time zones to end-users. User friendly time zones
 * are stored in the database for immediate changes in case of public time zone
 * changes.
 *
 * @author Hildeberto Mendonca - http://www.hildeberto.com
 */
@Entity
@Table(name = "timezone")
public class Timezone implements Serializable {
    private static final long serialVersionUID = 1L;
    private static final Integer INTERVAL_RAW_OFFSET = 3600000;
    private static final Integer MINUTE_SCALE = 60000;

    @Id
    private String id;

    @Column(name = "raw_offset")
    private Integer rawOffset;

    private String label;

    @Column(name = "default_tz")
    private Boolean defaultTz;

    public Timezone() {
        this.rawOffset = 0;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getOffset() {
        StringBuilder sb = new StringBuilder();
        Integer absRawOffset = Math.abs(this.rawOffset);

        if(this.rawOffset >= 0) {
            sb.append("+");
        }
        else {
            sb.append("-");
        }

        sb.append(String.format("%02d", absRawOffset / INTERVAL_RAW_OFFSET));

        sb.append(":");

        if((this.rawOffset % INTERVAL_RAW_OFFSET) != 0) {
            sb.append(String.format("%02d", (absRawOffset - ((absRawOffset / INTERVAL_RAW_OFFSET) * INTERVAL_RAW_OFFSET)) / MINUTE_SCALE));
        }
        else {
            sb.append("00");
        }

        return sb.toString();
    }

    public String getSign() {
        String sign;
        if(this.rawOffset >= 0) {
            sign = "+";
        }
        else {
            sign = "-";
        }
        return sign;
    }

    public void setSign(String sign) {
        switch(sign) {
            case "+":
                if(this.rawOffset < 0) {
                    this.rawOffset *= -1;
                }
                break;
            case "-":
                if(this.rawOffset >= 0) {
                    this.rawOffset *= -1;
                }
                break;
        }
    }

    public Integer getOffsetHour() {
        Integer absRawOffset = Math.abs(this.rawOffset);
        return absRawOffset / INTERVAL_RAW_OFFSET;
    }

    public void setOffsetHour(Integer offsetHour) {
        Integer rest = 0;
        if((this.rawOffset % INTERVAL_RAW_OFFSET) != 0) {
            Integer absRawOffset = Math.abs(this.rawOffset);
            rest = absRawOffset - ((absRawOffset / INTERVAL_RAW_OFFSET) * INTERVAL_RAW_OFFSET);
        }

        Integer newRawOffset = (offsetHour * INTERVAL_RAW_OFFSET) + rest;

        if(this.rawOffset >= 0) {
            this.rawOffset = newRawOffset;
        }
        else {
            this.rawOffset = newRawOffset * -1;
        }
    }

    public Integer getOffsetMinute() {
        Integer absRawOffset = Math.abs(this.rawOffset);
        Integer minutes = 0;
        if((this.rawOffset % INTERVAL_RAW_OFFSET) != 0) {
            minutes = (absRawOffset - ((absRawOffset / INTERVAL_RAW_OFFSET) * INTERVAL_RAW_OFFSET)) / MINUTE_SCALE;
        }
        return minutes;
    }

    public void setOffsetMinute(Integer offsetMinute) {
        Integer offsetHour = getOffsetHour();
        if(this.rawOffset >= 0) {
            this.rawOffset = (offsetHour * INTERVAL_RAW_OFFSET) + (offsetMinute * MINUTE_SCALE);
        }
        else {
            this.rawOffset = ((offsetHour * INTERVAL_RAW_OFFSET) + (offsetMinute * MINUTE_SCALE)) * -1;
        }
    }

    public String getLabel() {
        return label;
    }

    public String getOffsetLabel() {
        return "("+ getOffset() +") "+ this.label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public Boolean getDefaultTz() {
        return this.defaultTz;
    }

    public void setDefaultTz(Boolean defaultTz) {
        this.defaultTz = defaultTz;
    }

    public TimeZone getTimeZone() {
        return TimeZone.getTimeZone(this.id);
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        if (!(object instanceof Timezone)) {
            return false;
        }
        Timezone other = (Timezone) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "("+ getOffset() +") "+ this.label;
    }
}

src/main/java/org/cejug/yougi/partnership/web/controller/PartnershipMBean.java
/* Yougi is a web application conceived to manage user groups or
 * communities focused on a certain domain of knowledge, whose members are
 * constantly sharing information and participating in social and educational
 * events. Copyright (C) 2011 Hildeberto Mendonça.
 *
 * This application is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation; either version 2.1 of the License, or (at your
 * option) any later version.
 *
 * This application is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * There is a full copy of the GNU Lesser General Public License along with
 * this library. Look for the file license.txt at the root level. If you do not
 * find it, write to the Free Software Foundation, Inc., 59 Temple Place,
 * Suite 330, Boston, MA 02111-1307 USA.
 * */
package org.cejug.yougi.partnership.web.controller;

import org.cejug.yougi.entity.Province;
import org.cejug.yougi.entity.Properties;
import org.cejug.yougi.entity.Country;
import org.cejug.yougi.entity.UserAccount;
import org.cejug.yougi.entity.ApplicationProperty;
import org.cejug.yougi.entity.City;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import javax.faces.context.FacesContext;
import javax.servlet.http.HttpServletRequest;
import org.cejug.yougi.business.ApplicationPropertyBean;
import org.cejug.yougi.business.UserAccountBean;
import org.cejug.yougi.partnership.business.PartnerBean;
import org.cejug.yougi.partnership.business.RepresentativeBean;
import org.cejug.yougi.partnership.entity.Partner;
import org.cejug.yougi.partnership.entity.Representative;
import org.cejug.yougi.util.WebTextUtils;
import org.cejug.yougi.web.controller.LocationMBean;
import org.primefaces.event.FileUploadEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import org.primefaces.model.UploadedFile;

/**
 * @author Hildeberto Mendonca - http://www.hildeberto.com
 */
@ManagedBean
@RequestScoped
public class PartnershipMBean {

    static final Logger LOGGER = Logger.getLogger(PartnershipMBean.class.getSimpleName());

    @EJB
    private RepresentativeBean representativeBean;

    @EJB
    private UserAccountBean userAccountBean;

    @EJB
    private PartnerBean partnerBean;

    @EJB
    private ApplicationPropertyBean applicationPropertyBean;

    @ManagedProperty(value = "#{locationMBean}")
    private LocationMBean locationMBean;

    private Representative representative;

    private StreamedContent logoImage;

    public PartnershipMBean() {
    }

    public Representative getRepresentative() {
        return representative;
    }

    public void setRepresentative(Representative representative) {
        this.representative = representative;
    }

    public StreamedContent getLogoImage() {
        return logoImage;
    }

    public void setLogoImage(StreamedContent logoImage) {
        this.logoImage = logoImage;
    }

    public String getFormattedPartnerDescription() {
        if (representative != null) {
            String description = this.representative.getPartner().getDescription();
            return WebTextUtils.INSTANCE.convertLineBreakToHTMLParagraph(description);
        }
        return null;
    }

    public String getFormattedPartnerAddress() {
        Partner partner = this.representative.getPartner();
        return WebTextUtils.INSTANCE.printAddress(partner.getAddress(), partner.getCountry(), partner.getProvince(), partner.getCity(), partner.getPostalCode());
    }

    public boolean getRepresentativeExists() {
        if (this.representative.getId() != null) {
            return true;
        }
        return false;
    }

    public LocationMBean getLocationMBean() {
        return locationMBean;
    }

    public void setLocationMBean(LocationMBean locationMBean) {
        this.locationMBean = locationMBean;
    }

    @PostConstruct
    public void load() {
        HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
        String username = request.getRemoteUser();
        UserAccount person = userAccountBean.findByUsername(username);
        this.representative = representativeBean.findRepresentative(person);

        if (this.representative == null) {
            this.representative = new Representative();
            this.representative.setPerson(person);
            Partner newPartner = new Partner();
            this.representative.setPartner(newPartner);
        } else if (!locationMBean.isInitialized()) {
            locationMBean.initialize();

            if (this.representative.getPartner().getCountry() != null) {
                locationMBean.setSelectedCountry(this.representative.getPartner().getCountry().getAcronym());
            }

            if (this.representative.getPartner().getProvince() != null) {
                locationMBean.setSelectedProvince(this.representative.getPartner().getProvince().getId());
            }

            if (this.representative.getPartner().getCity() != null) {
                locationMBean.setSelectedCity(this.representative.getPartner().getCity().getId());
            }
        }

        loadLogoImage();
    }

    public String save() {
        Country country = this.locationMBean.getCountry();
        if (country != null) {
            this.representative.getPartner().setCountry(country);
        }

        Province province = this.locationMBean.getProvince();
        if (province != null) {
            this.representative.getPartner().setProvince(province);
        }

        City city = this.locationMBean.getCity();
        if (city != null) {
            this.representative.getPartner().setCity(city);
        }

        partnerBean.save(this.representative.getPartner());
        representativeBean.save(this.representative);

        FacesContext context = FacesContext.getCurrentInstance();
        context.getExternalContext().getSessionMap().remove("locationBean");

        return "profile?faces-redirect=true&tab=2";
    }

    public String remove() {
        representativeBean.remove(representative.getId());
        return "profile?faces-redirect=true";
    }

    private void loadLogoImage() {
        try {
            String logoPath = this.representative.getPartner().getLogo();

            if (logoPath != null) {
                InputStream in = new FileInputStream(new File(logoPath));
                LOGGER.log(Level.INFO, "JUG-0002: Loading logo file {0}", new String[]{logoPath});
                logoImage = new DefaultStreamedContent(in, "image/jpeg");
            }
        } catch (IOException e) {
            LOGGER.log(Level.SEVERE, e.getMessage(), e);
        }
    }

    public void handleLogoFileUpload(FileUploadEvent event) {
        UploadedFile uploadedFile = event.getFile();
        LOGGER.log(Level.INFO, "JUG-0001: File {0} of type {1} temporarely uploaded to {2}", new String[]{uploadedFile.getFileName(), uploadedFile.getContentType(), System.getProperty("java.io.tmpdir")});
        try {
            /* Loads the representative related to the logged user. */
            HttpServletRequest request = (HttpServletRequest) FacesContext.getCurrentInstance().getExternalContext().getRequest();
            String username = request.getRemoteUser();
            UserAccount person = userAccountBean.findByUsername(username);
            this.representative = representativeBean.findRepresentative(person);

            /* Write the inputStream to a FileOutputStream */
            InputStream in = uploadedFile.getInputstream();
            ApplicationProperty applicationProperty = applicationPropertyBean.findApplicationProperty(Properties.FILE_REPOSITORY_PATH);
            String fileExtension = uploadedFile.getFileName();
            fileExtension = fileExtension.substring(fileExtension.indexOf('.'));
            StringBuilder filePath = new StringBuilder();
            filePath.append(applicationProperty.getPropertyValue());
            filePath.append("/");
            filePath.append(this.representative.getPartner().getId());
            filePath.append(fileExtension);
            OutputStream out = new FileOutputStream(new File(filePath.toString()));
            int read;
            byte[] bytes = new byte[1024];

            while ((read = in.read(bytes)) != -1) {
                out.write(bytes, 0, read);
            }
            in.close();
            out.flush();
            out.close();

            /* If nothing goes wrong while saving the file,
             * then updates the database with the file location. */
            this.representative.getPartner().setLogo(filePath.toString());
            partnerBean.save(this.representative.getPartner());

            loadLogoImage();
        } catch (IOException ioe) {
            LOGGER.log(Level.INFO, ioe.getMessage(), ioe);
        } catch (Exception e) {
            LOGGER.log(Level.INFO, e.getMessage(), e);
        }
        FacesMessage msg = new FacesMessage("Succesful", uploadedFile.getSize() + " bytes of the file " + uploadedFile.getFileName() + " are uploaded.");
        FacesContext.getCurrentInstance().addMessage(null, msg);
    }

    public String removeLogoImage() {
        try {
            String logoPath = this.representative.getPartner().getLogo();

            if (logoPath != null) {
                File logo = new File(logoPath);

                logo.delete();

src/main/webapp/profile/change_email.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!-- Yougi is a web application conceived to manage user groups or
 * communities focused on a certain domain of knowledge, whose members are
 * constantly sharing information and participating in social and educational
 * events. Copyright (C) 2011 Hildeberto Mendonça.
 *
 * This application is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation; either version 2.1 of the License, or (at your
 * option) any later version.
 *
 * This application is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * There is a full copy of the GNU Lesser General Public License along with
 * this library. Look for the file license.txt at the root level. If you do not
 * find it, write to the Free Software Foundation, Inc., 59 Temple Place,
 * Suite 330, Boston, MA 02111-1307 USA.
 * -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <h:body>
        <ui:composition template="../layout.xhtml">
            <ui:define name="title">#{bundle.changeEmail}</ui:define>
            <ui:define name="content">
                <h1>#{bundle.changeEmail}</h1>
                <p><h:messages globalOnly="true" styleClass="alertMessage" infoClass="infoMessage" errorClass="errorMessage"/></p>

                <h:form>
                    <div class="form-group">
                        <h:outputLabel for="currentEmail" value="#{bundle.currentEmail} *" styleClass="control-label"/>
                        <h:inputText id="currentEmail" value="#{changeEmailMBean.currentEmail}" label="#{bundle.currentEmail}" size="40" maxlength="100" required="true" onchange="formatEmail(this)" styleClass="form-control"/>
                        <h:message for="currentEmail" errorClass="errorMessage"/>
                    </div>
                    <div class="form-group">
                        <h:outputLabel for="newEmail" value="#{bundle.newEmail} *" styleClass="control-label"/>
                        <h:inputText id="newEmail" label="#{bundle.newEmail}" required="true" size="40" maxlength="100" value="#{changeEmailMBean.newEmail}" onchange="formatEmail(this)" styleClass="form-control"/>
                        <h:message for="newEmail" errorClass="errorMessage"/>
                    </div>
                    <div class="form-group">
                        <h:outputLabel for="newEmailConfirmation" value="#{bundle.confirmEmail} *" styleClass="control-label"/>
                        <h:inputText id="newEmailConfirmation" autocomplete="off" label="#{bundle.confirmEmail}" required="true" size="40" maxlength="100" value="#{changeEmailMBean.newEmailConfirmation}" onchange="formatEmail(this)" styleClass="form-control"/>
                        <h:message for="newEmailConfirmation" errorClass="errorMessage"/>
                    </div>
                    <p/>
                    <h:commandButton value="#{bundle.changeEmail}" action="#{changeEmailMBean.changeEmail}" styleClass="btn btn-primary"/>
                    <h:button outcome="/change_email_confirmation" value="#{bundle.cancel}" styleClass="btn btn-default" style="margin-left: 5px;"/>
                </h:form>
                <script src="#{request.contextPath}/resources/js/jquery-1.10.2.min.js"></script>
            </ui:define>
        </ui:composition>
    </h:body>
</html>

src/main/webapp/profile/home.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!-- Yougi is a web application conceived to manage user groups or
 * communities focused on a certain domain of knowledge, whose members are
 * constantly sharing information and participating in social and educational
 * events. Copyright (C) 2011 Hildeberto Mendonça.
 *
 * This application is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation; either version 2.1 of the License, or (at your
 * option) any later version.
 *
 * This application is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * There is a full copy of the GNU Lesser General Public License along with
 * this library. Look for the file license.txt at the root level. If you do not
 * find it, write to the Free Software Foundation, Inc., 59 Temple Place,
 * Suite 330, Boston, MA 02111-1307 USA.
 * -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:ug="http://xmlns.jcp.org/jsf/composite/yougi">
    <body>
        <ui:composition template="../layout.xhtml">
            <ui:define name="title">#{bundle.personalData}</ui:define>
            <ui:define name="showcase">
                <ug:showcase/>
            </ui:define>
            <ui:define name="content">
                <ug:frontPage/>
            </ui:define>
        </ui:composition>
    </body>
</html>

src/main/webapp/profile/profile.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!-- Yougi is a web application conceived to manage user groups or
 * communities focused on a certain domain of knowledge, whose members are
 * constantly sharing information and participating in social and educational
 * events. Copyright (C) 2011 Hildeberto Mendonça.
 *
 * This application is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation; either version 2.1 of the License, or (at your
 * option) any later version.
 *
 * This application is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * There is a full copy of the GNU Lesser General Public License along with
 * this library. Look for the file license.txt at the root level. If you do not
 * find it, write to the Free Software Foundation, Inc., 59 Temple Place,
 * Suite 330, Boston, MA 02111-1307 USA.
 * -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <body>
        <ui:composition template="../layout.xhtml">
            <ui:define name="title">#{bundle.profile}</ui:define>
            <ui:define name="content">
                <h1>#{bundle.profile}</h1>
                <h:form>
                    <p:tabView dynamic="false" cache="true" activeIndex="#{param.tab}">
                        <p:tab title="#{bundle.personalData}">
                            <div class="row">
                                <div class="col-md-2">
                                    <h:graphicImage value="#{profilePictureFinder.getPictureFromEmail(userAccountMBean.userAccount.email)}" width="85" height="85"/>
                                </div>
                                <div class="col-md-10">
                                    <h:messages globalOnly="true" styleClass="alertMessage" infoClass="infoMessage" errorClass="errorMessage"/>

                                    <dl class="dl-horizontal">
                                        <dt><h:outputText value="#{bundle.firstName}"/></dt>
                                        <dd><h:outputText value="#{userAccountMBean.userAccount.firstName}"/></dd>
                                        <dt><h:outputText value="#{bundle.lastName}"/></dt>
                                        <dd><h:outputText value="#{userAccountMBean.userAccount.lastName}"/></dd>
                                        <dt><h:outputText value="#{bundle.gender}"/></dt>
                                        <dd><h:outputText value="#{userAccountMBean.userAccount.gender}">
                                                <f:converter converterId="GenderToString"/>
                                            </h:outputText></dd>
                                        <dt><h:outputText value="#{bundle.email}"/></dt>
                                        <dd><h:outputText value="#{userAccountMBean.userAccount.email}"/></dd>
                                        <dt><h:outputText value="#{bundle.website}"/></dt>
                                        <dd><h:outputLink value="http://#{userAccountMBean.userAccount.website}" target="_blank">#{userAccountMBean.userAccount.website}</h:outputLink></dd>
                                        <dt><h:outputText value="#{bundle.twitter}"/></dt>
                                        <dd><h:outputLink value="http://twitter.com/#{userAccountMBean.userAccount.twitter}" target="_blank">#{userAccountMBean.userAccount.twitter}</h:outputLink></dd>
                                        <dt><h:outputText value="#{bundle.publicProfile}"/></dt>
                                        <dd><h:outputText value="#{userAccountMBean.userAccount.publicProfile}"/></dd>
                                        <dt><h:outputText value="#{bundle.country}"/></dt>
                                        <dd><h:outputText value="#{userAccountMBean.userAccount.country}"/></dd>
                                        <dt><h:outputText value="#{bundle.province}"/></dt>
                                        <dd><h:outputText value="#{userAccountMBean.userAccount.province}"/></dd>
                                        <dt><h:outputText value="#{bundle.city}"/></dt>
                                        <dd><h:outputText value="#{userAccountMBean.userAccount.city}"/></dd>
                                        <dt><h:outputText value="#{bundle.timeZone}"/></dt>
                                        <dd><h:outputText value="#{userAccountMBean.userAccount.timeZone}"/></dd>
                                    </dl>

                                    <h:button outcome="member" value="#{bundle.update}" styleClass="btn btn-default" style="margin-right: 5px;"/>
                                    <h:button outcome="member_deactivation" value="#{bundle.deactivateMembership}" styleClass="btn btn-default"/>
                                </div>
                            </div>
                        </p:tab>
                        <p:tab title="#{bundle.attendedEvents}">
                            <h:dataTable value="" var="event">
                                <h:column>

                                </h:column>
                            </h:dataTable>
                        </p:tab>
                        <p:tab title="#{bundle.partnership}">
                            <h:panelGroup rendered="#{partnershipMBean.representativeExists}">
                                <h:graphicImage value="#{partnershipMBean.logoImage}" rendered="#{! empty partnershipMBean.logoImage}" />

                                <dl class="dl-horizontal">
                                    <dt><h:outputText value="#{bundle.name}"/></dt>
                                    <dd><h:outputText value="#{partnershipMBean.representative.partner.name}"/></dd>
                                    <dt><h:outputText value="#{bundle.description}"/></dt>
                                    <dd><h:outputText value="#{partnershipMBean.formattedPartnerDescription}" escape="false"/></dd>
                                    <dt><h:outputText value="#{bundle.website}"/></dt>
                                    <dd><h:outputLink value="#{partnershipMBean.representative.partner.url}" target="_blank">#{partnershipMBean.representative.partner.url}</h:outputLink></dd>
                                    <dt><h:outputText value="#{bundle.address}"/></dt>
                                    <dd><h:outputText value="#{partnershipMBean.formattedPartnerAddress}"/></dd>
                                    <dt><h:outputText value="#{bundle.representative}"/></dt>
                                    <dd><h:outputText value="#{partnershipMBean.representative.person}"/></dd>
                                    <dt><h:outputText value="#{bundle.position}"/></dt>
                                    <dd><h:outputText value="#{partnershipMBean.representative.position}"/></dd>
                                    <dt><h:outputText value="#{bundle.phone}"/></dt>
                                    <dd><h:outputText value="#{partnershipMBean.representative.phone}"/></dd>
                                </dl>

                                <h:button outcome="partnership" value="#{bundle.update}" styleClass="btn btn-default"/>
                                <h:button outcome="partnership_logo" value="#{bundle.changeLogo}" styleClass="btn btn-default"/>
                            </h:panelGroup>
                            <h:button outcome="partnership" value="#{bundle.becomePartner}" rendered="#{!partnershipMBean.representativeExists}" styleClass="btn btn-default"/>
                        </p:tab>
                    </p:tabView>
                </h:form>
            </ui:define>
            <ui:define name="jquery"></ui:define>
        </ui:composition>
    </body>
</html>