src/main/java/org/cejug/yougi/entity/PublicContent.java
/* Yougi is a web application conceived to manage user groups or
 * communities focused on a certain domain of knowledge, whose members are
 * constantly sharing information and participating in social and educational
 * events. Copyright (C) 2011 Hildeberto Mendonça.
 *
 * This application is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation; either version 2.1 of the License, or (at your
 * option) any later version.
 *
 * This application is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * There is a full copy of the GNU Lesser General Public License along with
 * this library. Look for the file license.txt at the root level. If you do not
 * find it, write to the Free Software Foundation, Inc., 59 Temple Place,
 * Suite 330, Boston, MA 02111-1307 USA.
 * */
package org.cejug.yougi.entity;

/**
 *
 * @author Hildeberto Mendonca - http://www.hildeberto.com
 */
public interface PublicContent {

    public String getId();

    public String getTitle();

    public String getAuthor();

    public String getContent();

    public String getSummary();

    public String getUrl();
}

src/main/java/org/cejug/yougi/entity/Timezone.java
/* Yougi is a web application conceived to manage user groups or
 * communities focused on a certain domain of knowledge, whose members are
 * constantly sharing information and participating in social and educational
 * events. Copyright (C) 2011 Hildeberto Mendonça.
 *
 * This application is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation; either version 2.1 of the License, or (at your
 * option) any later version.
 *
 * This application is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * There is a full copy of the GNU Lesser General Public License along with
 * this library. Look for the file license.txt at the root level. If you do not
 * find it, write to the Free Software Foundation, Inc., 59 Temple Place,
 * Suite 330, Boston, MA 02111-1307 USA.
 * */
package org.cejug.yougi.entity;

import java.io.Serializable;
import java.util.TimeZone;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Due to the user-unfriendly Java TimeZone implementation, this class was
 * created to represent friendly time zones to end-users. User friendly time zones
 * are stored in the database for immediate changes in case of public time zone
 * changes.
 *
 * @author Hildeberto Mendonca - http://www.hildeberto.com
 */
@Entity
@Table(name = "timezone")
public class Timezone implements Serializable {
    private static final long serialVersionUID = 1L;
    private static final Integer INTERVAL_RAW_OFFSET = 3600000;
    private static final Integer MINUTE_SCALE = 60000;

    @Id
    private String id;

    @Column(name = "raw_offset")
    private Integer rawOffset;

    private String label;

    @Column(name = "default_tz")
    private Boolean defaultTz;

    public Timezone() {
        this.rawOffset = 0;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getOffset() {
        StringBuilder sb = new StringBuilder();
        Integer absRawOffset = Math.abs(this.rawOffset);

        if(this.rawOffset >= 0) {
            sb.append("+");
        }
        else {
            sb.append("-");
        }

        sb.append(String.format("%02d", absRawOffset / INTERVAL_RAW_OFFSET));

        sb.append(":");

        if((this.rawOffset % INTERVAL_RAW_OFFSET) != 0) {
            sb.append(String.format("%02d", (absRawOffset - ((absRawOffset / INTERVAL_RAW_OFFSET) * INTERVAL_RAW_OFFSET)) / MINUTE_SCALE));
        }
        else {
            sb.append("00");
        }

        return sb.toString();
    }

    public String getSign() {
        String sign;
        if(this.rawOffset >= 0) {
            sign = "+";
        }
        else {
            sign = "-";
        }
        return sign;
    }

    public void setSign(String sign) {
        switch(sign) {
            case "+":
                if(this.rawOffset < 0) {
                    this.rawOffset *= -1;
                }
                break;
            case "-":
                if(this.rawOffset >= 0) {
                    this.rawOffset *= -1;
                }
                break;
        }
    }

    public Integer getOffsetHour() {
        Integer absRawOffset = Math.abs(this.rawOffset);
        return absRawOffset / INTERVAL_RAW_OFFSET;
    }

    public void setOffsetHour(Integer offsetHour) {
        Integer rest = 0;
        if((this.rawOffset % INTERVAL_RAW_OFFSET) != 0) {
            Integer absRawOffset = Math.abs(this.rawOffset);
            rest = absRawOffset - ((absRawOffset / INTERVAL_RAW_OFFSET) * INTERVAL_RAW_OFFSET);
        }

        Integer newRawOffset = (offsetHour * INTERVAL_RAW_OFFSET) + rest;

        if(this.rawOffset >= 0) {
            this.rawOffset = newRawOffset;
        }
        else {
            this.rawOffset = newRawOffset * -1;
        }
    }

    public Integer getOffsetMinute() {
        Integer absRawOffset = Math.abs(this.rawOffset);
        Integer minutes = 0;
        if((this.rawOffset % INTERVAL_RAW_OFFSET) != 0) {
            minutes = (absRawOffset - ((absRawOffset / INTERVAL_RAW_OFFSET) * INTERVAL_RAW_OFFSET)) / MINUTE_SCALE;
        }
        return minutes;
    }

    public void setOffsetMinute(Integer offsetMinute) {
        Integer offsetHour = getOffsetHour();
        if(this.rawOffset >= 0) {
            this.rawOffset = (offsetHour * INTERVAL_RAW_OFFSET) + (offsetMinute * MINUTE_SCALE);
        }
        else {
            this.rawOffset = ((offsetHour * INTERVAL_RAW_OFFSET) + (offsetMinute * MINUTE_SCALE)) * -1;
        }
    }

    public String getLabel() {
        return label;
    }

    public String getOffsetLabel() {
        return "("+ getOffset() +") "+ this.label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public Boolean getDefaultTz() {
        return this.defaultTz;
    }

    public void setDefaultTz(Boolean defaultTz) {
        this.defaultTz = defaultTz;
    }

    public TimeZone getTimeZone() {
        return TimeZone.getTimeZone(this.id);
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        if (!(object instanceof Timezone)) {
            return false;
        }
        Timezone other = (Timezone) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "("+ getOffset() +") "+ this.label;
    }
}

src/main/java/org/cejug/yougi/entity/UserAccount.java
/* Yougi is a web application conceived to manage user groups or
 * communities focused on a certain domain of knowledge, whose members are
 * constantly sharing information and participating in social and educational
 * events. Copyright (C) 2011 Hildeberto Mendonça.
 *
 * This application is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation; either version 2.1 of the License, or (at your
 * option) any later version.
 *
 * This application is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * There is a full copy of the GNU Lesser General Public License along with
 * this library. Look for the file license.txt at the root level. If you do not
 * find it, write to the Free Software Foundation, Inc., 59 Temple Place,
 * Suite 330, Boston, MA 02111-1307 USA.
 * */
package org.cejug.yougi.entity;

import java.io.Serializable;
import java.util.Date;
import java.util.UUID;
import javax.persistence.*;
import org.cejug.yougi.util.TextUtils;

/**
 * Represents the user account.
 *
 * @author Hildeberto Mendonca - http://www.hildeberto.com
 */
@Entity
@Table(name="user_account")
public class UserAccount implements Serializable, Identified {
    private static final long serialVersionUID = 1L;

    @Id
    private String id;

    @Column(name="first_name", nullable=false)
    private String firstName;

    @Column(name="last_name", nullable=false)
    private String lastName;

    @Enumerated(EnumType.ORDINAL)
    @Column(nullable=false)
    private Gender gender;

    private String email;

    @Transient
    private String emailConfirmation;

    @Column(name="unverified_email")
    private String unverifiedEmail;

    @Column(name="confirmation_code")
    private String confirmationCode;

    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name="registration_date")
    private Date registrationDate;

    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name="last_update")
    private Date lastUpdate;

    private Boolean deactivated = false;

    @Temporal(javax.persistence.TemporalType.TIMESTAMP)
    @Column(name="deactivation_date")
    private Date deactivationDate;

    @Column(name="deactivation_reason")
    private String deactivationReason;

    @Enumerated(EnumType.ORDINAL)
    @Column(name="deactivation_type")
    private DeactivationType deactivationType;

    private String website;

    private String twitter;

    @ManyToOne
    @JoinColumn(name="country")
    private Country country;

    @ManyToOne
    @JoinColumn(name="province")
    private Province province;

    @ManyToOne
    @JoinColumn(name="city")
    private City city;

    @Column(name="timezone")
    private String timeZone;

    @Column(name = "public_profile")
    private Boolean publicProfile;

    @Column(name = "mailing_list")
    private Boolean mailingList;

    private Boolean news;

    @Column(name="general_offer")
    private Boolean generalOffer;

    @Column(name = "job_offer")
    private Boolean jobOffer;

    private Boolean event;

    private Boolean sponsor;

    private Boolean speaker;

    private Boolean verified = false;

    public UserAccount() {}

    public UserAccount(String id) {
        this.id = id;
    }

    public UserAccount(String firstName, String lastName, String email) {
        this.firstName = firstName;
        this.lastName = lastName;
        this.email = email;
    }

    @Override
    public String getId() {
        return this.id;
    }

    @Override
    public void setId(String id) {
        this.id = id;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = TextUtils.INSTANCE.capitalizeFirstCharWords(firstName);
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = TextUtils.INSTANCE.capitalizeFirstCharWords(lastName);
    }

    public String getFullName() {
        StringBuilder str = new StringBuilder();
        str.append(firstName);
        str.append(" ");
        str.append(lastName);
        return str.toString();
    }

    public Gender getGender() {
        return gender;
    }

    public void setGender(Gender gender) {
        this.gender = gender;
    }

    /**
     * @return the email address of the user. Despite its validity, do not use
     * the returned value to send email messages to the user. Use getPostingEmail() instead.
     * @see #getPostingEmail()
     */
    public String getEmail() {
        return email;
    }

    /**
     * @return the unverifiedEmail is not null when the user's email is not
     * confirmed yet. Once the email is confirmed this method returns null.
     */
    public String getUnverifiedEmail() {
        return unverifiedEmail;
    }

    public void setUnverifiedEmail(String unverifiedEmail) {
        if(unverifiedEmail != null) {
            this.unverifiedEmail = unverifiedEmail.toLowerCase();
        }
        else {
            this.unverifiedEmail = null;
        }
    }

    /**
     * Update the email with the value of the unverified email and clean the
     * unverifiedEmail.
     */
    public void setEmailAsVerified() {
        this.email = this.unverifiedEmail;
        this.unverifiedEmail = null;
    }

    /**
     * @return Independent of the verification of the email, this method returns
     * the available email address for posting email messages.
     */
    public String getPostingEmail() {
        // In case there is an unverified email, it has the priority to be in
        // the message recipient.
        if(this.unverifiedEmail != null && !this.unverifiedEmail.isEmpty()) {
            return this.unverifiedEmail;
        }
        // If unverified email is null it means that the email is valid and it
        // can be used in the message recipient.
        else {
            return this.email;
        }
    }

    public Date getRegistrationDate() {
        return registrationDate;
    }

    public void setRegistrationDate(Date registrationDate) {
        this.registrationDate = registrationDate;
    }

    public Date getLastUpdate() {
        return lastUpdate;
    }

    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    public Boolean getDeactivated() {
        if(deactivated != null) {
            return deactivated;
        }
        else {
            return false;
        }
    }

    public void setDeactivated(Boolean deactivated) {
        this.deactivated = deactivated;
    }

    public Date getDeactivationDate() {
        return deactivationDate;
    }

    public void setDeactivationDate(Date deactivationDate) {
        this.deactivationDate = deactivationDate;
    }

    public String getDeactivationReason() {
        return deactivationReason;
    }

    public void setDeactivationReason(String deactivationReason) {
        this.deactivationReason = deactivationReason;
    }

    public DeactivationType getDeactivationType() {
        return deactivationType;
    }

    public void setDeactivationType(DeactivationType deactivationType) {
        this.deactivationType = deactivationType;
    }

    public String getWebsite() {
        return website;
    }

    public void setWebsite(String website) {
        if(website == null || website.trim().isEmpty()) {
            this.website = null;
        }
        else if(website.contains("http://")) {
            this.website = website.replace("http://", "");
        }
        else if(website.contains("https://")) {
            this.website = website.replace("https://", "");
        }
        else {
            this.website = website;
        }
    }

    public String getTwitter() {
        return twitter;
    }

    public void setTwitter(String twitter) {
        if(twitter == null || twitter.trim().isEmpty()) {
            this.twitter = null;
        }
        else if(twitter.contains("@")) {
            this.twitter = twitter.replace("@", "");
        }
        else {
            this.twitter = twitter;
        }
    }

    public Country getCountry() {
        return country;
    }

    public void setCountry(Country country) {
        this.country = country;
    }

    public Province getProvince() {
        return province;
    }

    public void setProvince(Province province) {
        this.province = province;
    }

    public City getCity() {
        return city;
    }

    public void setCity(City city) {
        this.city = city;
    }

    /**
     * @return the timezone from where the user is located. It is automatically
     * set based on the city where the user is located.
     */
    public String getTimeZone() {
        return timeZone;
    }

    public void setTimeZone(String timeZone) {
        this.timeZone = timeZone;
    }

    public Boolean getSpeaker() {
        return speaker;
    }

    public void setSpeaker(Boolean speaker) {
        this.speaker = speaker;
    }

    /**
     * A new user, who had his/er email confirmed, is by default unverified.
     * @return this method returns false by default. An administrator may check
     * whether the data of the new user does not sound strange, something that
     * might be consider as a tester or a spammer. But, if all data seem ok,
     * then administrator can mark the user as verified. In this case, this
     * method returns true.
     */
    public Boolean getVerified() {
        return verified;
    }

    public void setVerified(Boolean verified) {
        this.verified = verified;
    }

    public Boolean getPublicProfile() {
        return publicProfile;
    }

src/main/webapp/admin/countries.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!-- Yougi is a web application conceived to manage user groups or
 * communities focused on a certain domain of knowledge, whose members are
 * constantly sharing information and participating in social and educational
 * events. Copyright (C) 2011 Hildeberto Mendonça.
 *
 * This application is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation; either version 2.1 of the License, or (at your
 * option) any later version.
 *
 * This application is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * There is a full copy of the GNU Lesser General Public License along with
 * this library. Look for the file license.txt at the root level. If you do not
 * find it, write to the Free Software Foundation, Inc., 59 Temple Place,
 * Suite 330, Boston, MA 02111-1307 USA.
 * -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui">
    <h:body>
        <ui:composition template="../layout.xhtml">
            <ui:define name="title">#{bundle.countries}</ui:define>
            <ui:define name="content">
                <h1>#{bundle.countries}</h1>
                <p><h:link outcome="country" value="#{bundle.new} #{bundle.country}"/></p>
                <h:form>
                    <h:dataTable value="#{countryMBean.countries}" var="country" styleClass="table table-striped table-bordered">
                        <h:column>
                            <f:facet name="header"><h:outputText value="#{bundle.name}"/></f:facet>
                            <h:link outcome="country" value="#{country.name}">
                                <f:param name="acronym" value="#{country.acronym}"/>
                            </h:link>
                        </h:column>
                        <h:column>
                            <f:facet name="header"><h:outputText value="#{bundle.acronym}"/></f:facet>
                            <h:outputText value="#{country.acronym}"/>
                        </h:column>
                    </h:dataTable>
                </h:form>
            </ui:define>
            <ui:define name="jquery"></ui:define>
        </ui:composition>
    </h:body>
</html>

src/main/webapp/admin/country.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!-- Yougi is a web application conceived to manage user groups or
 * communities focused on a certain domain of knowledge, whose members are
 * constantly sharing information and participating in social and educational
 * events. Copyright (C) 2011 Hildeberto Mendonça.
 *
 * This application is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation; either version 2.1 of the License, or (at your
 * option) any later version.
 *
 * This application is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * There is a full copy of the GNU Lesser General Public License along with
 * this library. Look for the file license.txt at the root level. If you do not
 * find it, write to the Free Software Foundation, Inc., 59 Temple Place,
 * Suite 330, Boston, MA 02111-1307 USA.
 * -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <body>
        <ui:composition template="../layout.xhtml">
            <ui:define name="title">#{bundle.country}</ui:define>
            <ui:define name="content">
                <h1>#{bundle.country}</h1>
                <h:form>
                    <h:messages globalOnly="true" styleClass="alertMessage" infoClass="infoMessage" errorClass="errorMessage"/>
                    <div class="form-group">
                        <h:outputLabel for="name" value="#{bundle.name}" styleClass="control-label"/>
                        <h:inputText id="name" label="#{bundle.name}" required="true" size="100" maxlength="100" value="#{countryMBean.country.name}" styleClass="form-control">
                           <f:validateRegex pattern="[a-zA-Z]+"/>
                        </h:inputText>   
                        <h:message for="name" errorClass="errorMessage"/>
                    </div>
					<div class="form-group">
                        <h:outputLabel for="acronym" value="#{bundle.acronym}" styleClass="control-label"/>
                        <h:inputText id="acronym"  label="#{bundle.acronym}" required="true" size="3" maxlength="3" value="#{countryMBean.country.acronym}" styleClass="form-control" >
                            <f:validateRegex pattern="[a-zA-Z]+"/>
                        </h:inputText>
                        <h:message for="acronym" errorClass="errorMessage"/>
                    </div>
					<p/>
                        <h:commandButton value="#{bundle.save}" action="#{countryMBean.save}" styleClass="btn btn-primary"/>
                        <h:commandButton value="#{bundle.remove}" rendered="#{not empty param.acronym}" action="#{countryMBean.remove}"  styleClass="btn btn-warning" onclick="return confirmAction('#{bundle.warnCode0005}');">
                            <f:param name="acronym" value="#{countryMBean.country.acronym}" />
                        </h:commandButton>
                        <h:button outcome="countries" value="#{bundle.cancel}" styleClass="btn btn-default" style="margin-left: 5px;"/>
                </h:form>
            </ui:define>
        </ui:composition>
    </body>
</html>

src/main/webapp/admin/group.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!-- Yougi is a web application conceived to manage user groups or
 * communities focused on a certain domain of knowledge, whose members are
 * constantly sharing information and participating in social and educational
 * events. Copyright (C) 2011 Hildeberto Mendonça.
 *
 * This application is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation; either version 2.1 of the License, or (at your
 * option) any later version.
 *
 * This application is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * There is a full copy of the GNU Lesser General Public License along with
 * this library. Look for the file license.txt at the root level. If you do not
 * find it, write to the Free Software Foundation, Inc., 59 Temple Place,
 * Suite 330, Boston, MA 02111-1307 USA.
 * -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui">
    <body>
        <ui:composition template="../layout.xhtml">
            <ui:define name="title">#{bundle.group}</ui:define>
            <ui:define name="content">
                <h1>#{bundle.group}</h1>
                <h:form>
                    <h:messages globalOnly="true" styleClass="alertMessage" infoClass="infoMessage" errorClass="errorMessage"/>
                    <h:panelGrid columns="2" columnClasses="panelGridColumn">
                        <h:outputText value="#{bundle.properties}" styleClass="header3"/>
                        <h:outputText value="#{bundle.members}" styleClass="header3"/>

                        <h:panelGrid columns="1">
                            <h:outputLabel for="name" value="#{bundle.name}" styleClass="mandatoryField"/>
                            <h:inputText id="name" label="#{bundle.name}" required="true" size="30" maxlength="100" value="#{accessGroupMBean.group.name}"/>
                            <h:message for="name" errorClass="errorMessage"/>

                            <h:outputLabel for="description" value="#{bundle.description}"/>
                            <h:inputText id="description" label="#{bundle.description}" size="30" maxlength="100" value="#{accessGroupMBean.group.description}"/>
                            <h:message for="description" errorClass="errorMessage"/>

                            <h:panelGrid columns="2">
                                <h:selectBooleanCheckbox id="default" label="#{bundle.default}" value="#{accessGroupMBean.group.userDefault}"/>
                                <h:outputLabel for="default" value="#{bundle.default}"/>
                            </h:panelGrid>
                        </h:panelGrid>
                        <p:pickList id="members" value="#{accessGroupMBean.members}" var="member" itemLabel="#{member.fullName}" itemValue="#{member.id}" converter="GroupPickListConverter"/>
                        <br/><h:message for="members" errorClass="errorMessage"/>
                    </h:panelGrid>

                    <h:inputHidden id="id" value="#{accessGroupMBean.group.id}"/>

                    <h:panelGrid columns="3">
                        <h:commandButton value="#{bundle.save}" action="#{accessGroupMBean.save}"/>
                        <h:button outcome="groups" value="#{bundle.cancel}"/>
                    </h:panelGrid>
                </h:form>
            </ui:define>
            <ui:define name="jquery"></ui:define>
        </ui:composition>
    </body>
</html>

src/main/webapp/admin/job_schedulers.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!-- Yougi is a web application conceived to manage user groups or
 * communities focused on a certain domain of knowledge, whose members are
 * constantly sharing information and participating in social and educational
 * events. Copyright (C) 2011 Hildeberto Mendonça.
 *
 * This application is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation; either version 2.1 of the License, or (at your
 * option) any later version.
 *
 * This application is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * There is a full copy of the GNU Lesser General Public License along with
 * this library. Look for the file license.txt at the root level. If you do not
 * find it, write to the Free Software Foundation, Inc., 59 Temple Place,
 * Suite 330, Boston, MA 02111-1307 USA.
 * -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <h:body>
        <ui:composition template="../layout.xhtml">
            <ui:define name="title">#{bundle.jobs}</ui:define>
            <ui:define name="content">
                <div class="page-header">
                    <h1>#{bundle.jobs}</h1>
                </div>
                <h:form>
                    <h:dataTable value="#{jobSchedulerMBean.jobSchedulers}" var="jobScheduler" styleClass="table">
                        <f:facet name="header">
                            <h:button outcome="job_scheduler_form" value="#{bundle.new}" styleClass="btn btn-default"/>
                        </f:facet>
                        <h:column>
                            <f:facet name="header"><h:outputText value="#{bundle.url}"/></f:facet>
                            <h:link outcome="job_scheduler" value="#{jobScheduler.name}">
                                <f:param name="id" value="#{jobScheduler.id}"/>
                            </h:link>
                        </h:column>
                        <h:column>
                            <f:facet name="header"><h:outputText value="#{bundle.owner}"/></f:facet>
                            <h:outputText value="#{jobScheduler.defaultOwner}"/>
                        </h:column>
                        <h:column>
                            <f:facet name="header"><h:outputText value="#{bundle.startDate}"/></f:facet>
                            <h:outputText value="#{jobScheduler.startDate}">
                                <f:convertDateTime pattern="dd/MM/yyyy"/>
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header"><h:outputText value="#{bundle.endDate}"/></f:facet>
                            <h:outputText value="#{jobScheduler.endDate}">
                                <f:convertDateTime pattern="dd/MM/yyyy"/>
                            </h:outputText>
                        </h:column>
                        <h:column>
                            <f:facet name="header"><h:outputText value="#{bundle.time}"/></f:facet>
                            <h:outputText value="#{jobScheduler.startTime}">
                                <f:convertDateTime pattern="HH:mm"/>
                            </h:outputText>
                        </h:column>
                    </h:dataTable>
                </h:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>