src/main/java/org/cejug/yougi/knowledge/entity/Article.java
/* Yougi is a web application conceived to manage user groups or
 * communities focused on a certain domain of knowledge, whose members are
 * constantly sharing information and participating in social and educational
 * events. Copyright (C) 2011 Hildeberto Mendonça.
 *
 * This application is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation; either version 2.1 of the License, or (at your
 * option) any later version.
 *
 * This application is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * There is a full copy of the GNU Lesser General Public License along with
 * this library. Look for the file license.txt at the root level. If you do not
 * find it, write to the Free Software Foundation, Inc., 59 Temple Place,
 * Suite 330, Boston, MA 02111-1307 USA.
 * */
package org.cejug.yougi.knowledge.entity;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import org.cejug.yougi.entity.Identified;
import org.cejug.yougi.entity.PublicContent;
import org.cejug.yougi.util.StringUtils;

/**
 * Entity class representing an extracted article from a web source, making it
 * permanently available for publication.
 *
 * @author Hildeberto Mendonca - http://www.hildeberto.com
 */
@Entity
@Table(name = "article")
public class Article implements Serializable, Identified, PublicContent {
    private static final long serialVersionUID = 1L;

    @Id
    private String id;
    private String title;
    private String author;

    @ManyToOne
    @JoinColumn(name="web_source")
    private WebSource webSource;

    private String content;
    private String summary;

    @Column(name="perm_link")
    private String permanentLink;

    private String topics;

    @Temporal(javax.persistence.TemporalType.DATE)
    private Date publication;

    private Boolean published;

    public Article() {}

    public Article(String id) {
        this.id = id;
    }

    public Article(String id, String permanentLink) {
        this.id = id;
        this.permanentLink = permanentLink;
    }

    @Override
    public String getId() {
        return id;
    }

    @Override
    public void setId(String id) {
        this.id = id;
    }

    @Override
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    @Override
    public String getAuthor() {
        return author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }

    public WebSource getWebSource() {
        return webSource;
    }

    public void setWebSource(WebSource webSource) {
        this.webSource = webSource;
    }

    @Override
    public String getContent() {
        return content;
    }

    public void setContent(String content) {
        this.content = content;
    }

    @Override
    public String getSummary() {
        return summary;
    }

    public void setSummary(String summary) {
        this.summary = summary;
    }

    @Override
    public String getUrl() {
        return "/knowledge/article";
    }

    /**
     * @return Returns the content if it exists or the summary if the content
     * doesn't exist.
     */
    public String getText() {
        if(StringUtils.INSTANCE.isNullOrBlank(this.content)) {
            return this.summary;
        }
        else {
            return this.content;
        }
    }

    public String getPermanentLink() {
        return permanentLink;
    }

    public void setPermanentLink(String permanentLink) {
        this.permanentLink = permanentLink;
    }

    public String getTopics() {
        return topics;
    }

    public void setTopics(String topics) {
        this.topics = topics;
    }

    public Date getPublication() {
        return publication;
    }

    public void setPublication(Date publication) {
        this.publication = publication;
    }

    public Boolean getPublished() {
        return published;
    }

    public void setPublished(Boolean published) {
        this.published = published;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        if (!(object instanceof Article)) {
            return false;
        }
        boolean equals = false;
        Article other = (Article) object;

        if(this.id != null && other.id != null) {
            equals = this.id.equals(other.id);
        }
        else if(this.permanentLink != null) {
            equals = this.permanentLink.equals(other.permanentLink);
        }

        return equals;
    }

    @Override
    public String toString() {
        return this.title;
    }
}

src/main/java/org/cejug/yougi/knowledge/business/MailingListBean.java
/* Yougi is a web application conceived to manage user groups or
 * communities focused on a certain domain of knowledge, whose members are
 * constantly sharing information and participating in social and educational
 * events. Copyright (C) 2011 Hildeberto Mendonça.
 *
 * This application is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation; either version 2.1 of the License, or (at your
 * option) any later version.
 *
 * This application is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * There is a full copy of the GNU Lesser General Public License along with
 * this library. Look for the file license.txt at the root level. If you do not
 * find it, write to the Free Software Foundation, Inc., 59 Temple Place,
 * Suite 330, Boston, MA 02111-1307 USA.
 * */
package org.cejug.yougi.knowledge.business;

import java.util.List;
import java.util.logging.Logger;
import javax.ejb.Stateless;
import javax.persistence.EntityManager;
import javax.persistence.NoResultException;
import javax.persistence.PersistenceContext;
import org.cejug.yougi.business.AbstractBean;
import org.cejug.yougi.knowledge.entity.MailingList;

/**
 * Implements the business logic related to the management of mailing lists.
 *
 * @author Hildeberto Mendonca - http://www.hildeberto.com
 */
@Stateless
public class MailingListBean extends AbstractBean<MailingList> {

    @PersistenceContext
    private EntityManager em;

    static final Logger LOGGER = Logger.getLogger(MailingListBean.class.getName());

    public MailingListBean() {
        super(MailingList.class);
    }

    @Override
    protected EntityManager getEntityManager() {
        return em;
    }

    public List<MailingList> findMailingLists() {
        return em.createQuery("select ml from MailingList ml order by ml.name asc", MailingList.class).getResultList();
    }

    public MailingList findMailingListByEmail(String email) {
        try {
            return (MailingList) em.createQuery("select ml from MailingList ml where ml.email = :email")
                                   .setParameter("email", email)
                                   .getSingleResult();
        }
        catch(NoResultException nre) {
            return null;
        }
    }
}

src/main/java/org/cejug/yougi/knowledge/web/controller/TopicMBean.java
/* Yougi is a web application conceived to manage user groups or
 * communities focused on a certain domain of knowledge, whose members are
 * constantly sharing information and participating in social and educational
 * events. Copyright (C) 2011 Hildeberto Mendonça.
 *
 * This application is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation; either version 2.1 of the License, or (at your
 * option) any later version.
 *
 * This application is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * There is a full copy of the GNU Lesser General Public License along with
 * this library. Look for the file license.txt at the root level. If you do not
 * find it, write to the Free Software Foundation, Inc., 59 Temple Place,
 * Suite 330, Boston, MA 02111-1307 USA.
 * */
package org.cejug.yougi.knowledge.web.controller;

import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import org.cejug.yougi.knowledge.business.TopicBean;
import org.cejug.yougi.knowledge.entity.Topic;

/**
 * @author Hildeberto Mendonca - http://www.hildeberto.com
 */
@ManagedBean
@RequestScoped
public class TopicMBean {

    @EJB
    private TopicBean topicBean;

    private Topic topic;

    private List<Topic> topics;

    @ManagedProperty(value="#{param.topic}")
    private String topicName;
    
    private Boolean topicExistent = Boolean.FALSE;

    public TopicMBean() {
        this.topic = new Topic();
    }

    public String getTopicName() {
        return topicName;
    }

    public void setTopicName(String topicName) {
        this.topicName = topicName;
    }

    public Topic getTopic() {
        return topic;
    }

    public void setTopic(Topic topic) {
        this.topic = topic;
    }

    public List<Topic> getTopics() {
        if(this.topics == null) {
            this.topics = topicBean.findTopics();
        }
        return this.topics;
    }
    
    public Boolean getExistent() {
        return this.topicExistent;
    }

    @PostConstruct
    public void load() {
        if(this.topicName != null && !this.topicName.isEmpty()) {
            this.topic = topicBean.findTopic(topicName);
            if(this.topic != null) {
                this.topicExistent = true;
            }
        }
    }

    public String save() {
        topicBean.save(this.topic);
        return "topics?faces-redirect=true";
    }

    public String remove() {
        topicBean.remove(this.topic.getName());
        return "topics?faces-redirect=true";
    }
}

src/main/java/org/cejug/yougi/knowledge/web/controller/WebSourceMBean.java
/* Yougi is a web application conceived to manage user groups or
 * communities focused on a certain domain of knowledge, whose members are
 * constantly sharing information and participating in social and educational
 * events. Copyright (C) 2011 Hildeberto Mendonça.
 *
 * This application is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation; either version 2.1 of the License, or (at your
 * option) any later version.
 *
 * This application is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * There is a full copy of the GNU Lesser General Public License along with
 * this library. Look for the file license.txt at the root level. If you do not
 * find it, write to the Free Software Foundation, Inc., 59 Temple Place,
 * Suite 330, Boston, MA 02111-1307 USA.
 * */
package org.cejug.yougi.knowledge.web.controller;

import java.util.List;
import javax.annotation.PostConstruct;
import javax.ejb.EJB;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.RequestScoped;
import org.cejug.yougi.business.UserAccountBean;
import org.cejug.yougi.entity.UserAccount;
import org.cejug.yougi.knowledge.business.ArticleBean;
import org.cejug.yougi.knowledge.business.WebSourceBean;
import org.cejug.yougi.knowledge.entity.Article;
import org.cejug.yougi.knowledge.entity.WebSource;
import org.cejug.yougi.util.UrlUtils;

/**
 * @author Hildeberto Mendonca - http://www.hildeberto.com
 */
@ManagedBean
@RequestScoped
public class WebSourceMBean {

    @EJB
    private UserAccountBean userAccountBean;

    @EJB
    private WebSourceBean webSourceBean;

    @EJB
    private ArticleBean articleBean;

    private WebSource webSource;

    private List<WebSource> webSources;
    private List<Article> publishedArticles;

    private List<UserAccount> membersWithWebsite;
    private String selectedMember;
    private String website;

    @ManagedProperty(value="#{param.id}")
    private String id;

    @ManagedProperty(value="#{unpublishedArticlesMBean}")
    private UnpublishedArticlesMBean unpublishedArticlesMBean;

    public WebSource getWebSource() {
        return this.webSource;
    }

    public String getId() {
        return id;
    }

    public void setId(String userId) {
        this.id = userId;
    }

    public List<WebSource> getWebSources() {
        if(this.webSources == null) {
            this.webSources = webSourceBean.findWebResources();
        }
        return this.webSources;
    }

    public List<UserAccount> getMembersWithWebsite() {
        if(this.membersWithWebsite == null) {
            this.membersWithWebsite = webSourceBean.findNonReferencedProviders();
        }
        return this.membersWithWebsite;
    }

    public String getSelectedMember() {
        return this.selectedMember;
    }

    public void setSelectedMember(String selectedMember) {
        this.selectedMember = selectedMember;
    }

    public String getWebsite() {
        if(this.selectedMember != null && !this.selectedMember.isEmpty() && this.website == null) {
            this.webSource.setProvider(userAccountBean.find(this.selectedMember));
            this.website = this.webSource.getProvider().getWebsite();
            this.website = UrlUtils.INSTANCE.setProtocol(this.website);
        }
        return this.website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    public String getTitle() {
        if(this.selectedMember != null && !this.selectedMember.isEmpty() && this.webSource.getTitle() == null) {
            this.webSource = webSourceBean.loadWebSource(this.webSource);
        }
        return this.webSource.getTitle();
    }

    public void setTitle(String title) {
        this.webSource.setTitle(title);
    }

    public String getFeed() {
        if(this.selectedMember != null && !this.selectedMember.isEmpty() && this.webSource.getFeed() == null) {
            this.webSource = webSourceBean.loadWebSource(this.webSource);
        }
        return this.webSource.getFeed();
    }

    public void setFeed(String feed) {
        this.webSource.setFeed(feed);
    }

    public void updateWebSource() {
        this.webSource = webSourceBean.loadWebSource(this.website);
        UserAccount userAccount = userAccountBean.findByWebsite(this.website);
        if(userAccount != null) {
            this.selectedMember = userAccount.getId();
        }
    }

    public List<Article> getPublishedArticles() {
        if(publishedArticles == null) {
            this.publishedArticles = articleBean.findPublishedArticles(this.webSource);
        }
        return this.publishedArticles;
    }

    public void setUnpublishedArticlesMBean(UnpublishedArticlesMBean unpublishedArticlesMBean) {
        this.unpublishedArticlesMBean = unpublishedArticlesMBean;
    }

    public List<Article> getUnpublishedArticles() {
        if(unpublishedArticlesMBean.getUnpublishedArticles() == null) {
            unpublishedArticlesMBean.setUnpublishedArticles(webSourceBean.loadUnpublishedArticles(this.webSource));
        }
        return this.unpublishedArticlesMBean.getUnpublishedArticles();
    }

    @PostConstruct
    public void load() {
        if(this.id != null && !this.id.isEmpty()) {
            this.webSource = webSourceBean.find(this.id);
            if(this.webSource.getProvider() != null) {
                this.selectedMember = this.webSource.getProvider().getId();
            }
            unpublishedArticlesMBean.setWebSource(this.webSource);
        }
        else {
            this.webSource = new WebSource();
        }
    }

    public String save() {
        if(this.selectedMember != null && !this.selectedMember.isEmpty()) {
            this.webSource.setProvider(userAccountBean.find(this.selectedMember));
        }
        webSourceBean.save(this.webSource);
        return "web_sources";
    }

    public String undoReference() {
        webSourceBean.remove(this.webSource.getId());
        this.webSource.setId(null);
        return "web_sources";
    }
}

src/main/webapp/knowledge/article.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!-- Yougi is a web application conceived to manage user groups or
 * communities focused on a certain domain of knowledge, whose members are
 * constantly sharing information and participating in social and educational
 * events. Copyright (C) 2011 Hildeberto Mendonça.
 *
 * This application is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation; either version 2.1 of the License, or (at your
 * option) any later version.
 *
 * This application is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * There is a full copy of the GNU Lesser General Public License along with
 * this library. Look for the file license.txt at the root level. If you do not
 * find it, write to the Free Software Foundation, Inc., 59 Temple Place,
 * Suite 330, Boston, MA 02111-1307 USA.
 * -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:c="http://xmlns.jcp.org/jsp/jstl/core"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <body>
        <ui:composition template="../layout.xhtml">
            <ui:define name="title">#{bundle.article}</ui:define>
            <ui:define name="content">
                <div class="row">
                    <div class="col-md-1">
                        <h:graphicImage value="#{profilePictureFinder.getPictureFromEmail(articleMBean.article.webSource.provider.email)}" style="margin-right: 10px;" width="85" height="85"/>
                    </div>
                    <div class="col-md-7">
                        <h:outputText value="#{articleMBean.article}" style="font-size: 26px; font-weight: bold; color: steelblue;"/><br/>
                        <h:outputText value="#{bundle.by} "/>
                        <h:outputLink value="http://#{articleMBean.article.webSource.provider.website}" rendered="#{! empty articleMBean.article.webSource.provider.website}" target="_blank" style="font-size: 18px;">
                            <h:outputText value="#{articleMBean.article.author}"/>
                        </h:outputLink>
                        <h:outputText value="#{articleMBean.article.author}" rendered="#{empty articleMBean.article.webSource.provider.website}"/>
                        <br/>
                        <h:outputText value="#{articleMBean.article.summary}" escape="false" styleClass="lead"/>
                        <p/>
                        <h:outputText value="#{articleMBean.article.text}" escape="false" style="font-size: 14px;"/>
                    </div>
                    <div class="col-md-4">
                        <div class="panel panel-default">
                            <div class="panel-heading">#{bundle.articlesSameSource}</div>
                            <div class="panel-body">
                                <ul>
                                    <c:forEach var="article" items="#{articleMBean.articlesFromSameSource}">
                                        <li>
                                            <h:link outcome="article" value="#{article.title}">
                                                <f:param name="id" value="#{article.id}"/>
                                            </h:link>
                                        </li>
                                    </c:forEach>
                                </ul>
                            </div>
                        </div>

                        <div class="panel panel-default">
                            <div class="panel-heading">#{bundle.articlesRecentlyPublished}</div>
                            <div class="panel-body">
                                <ul>
                                    <c:forEach var="article" items="#{articleMBean.otherPublishedArticles}">
                                        <li>
                                            <h:link outcome="article" value="#{article.title}">
                                                <f:param name="id" value="#{article.id}"/>
                                            </h:link>
                                        </li>
                                    </c:forEach>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </ui:define>
        </ui:composition>
    </body>
</html>

src/main/webapp/knowledge/topic.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!-- Yougi is a web application conceived to manage user groups or
 * communities focused on a certain domain of knowledge, whose members are
 * constantly sharing information and participating in social and educational
 * events. Copyright (C) 2011 Hildeberto Mendonça.
 *
 * This application is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation; either version 2.1 of the License, or (at your
 * option) any later version.
 *
 * This application is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * There is a full copy of the GNU Lesser General Public License along with
 * this library. Look for the file license.txt at the root level. If you do not
 * find it, write to the Free Software Foundation, Inc., 59 Temple Place,
 * Suite 330, Boston, MA 02111-1307 USA.
 * -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <body>
        <ui:composition template="../layout.xhtml">
            <ui:define name="title">#{bundle.topic}</ui:define>
            <ui:define name="content">
                <h1>#{bundle.topic}: #{topicMBean.topic}</h1>
                    <div  class="form-group">
                    	<h:outputLabel for="name" value="#{bundle.name} *" styleClass="control-label"/>
                    	<h:inputText id="name" label="#{bundle.name}" required="true" size="20" maxlength="20" value="#{topicMBean.topic.name}" readonly="#{! empty topicMBean.topic.name}" styleClass="form-control"/>
                        <h:message for="name" errorClass="errorMessage"/>
                    </div>
                    <div class="form-group">
                        <h:outputLabel for="label" value="#{bundle.label} *" styleClass="control-label"/>
                        <h:inputText id="label" label="#{bundle.label}" required="true" size="20" maxlength="20" value="#{topicMBean.topic.label}" styleClass="form-control"/>
                        <h:message for="label" errorClass="errorMessage"/>
                    </div>
                    <div class="form-group">
                        <h:selectBooleanCheckbox id="valid" label="#{bundle.valid}" value="#{topicMBean.topic.valid}"/>
                        <h:outputLabel for="valid" value="#{bundle.valid}"/>
                    </div>
                    <div class="form-group">
                    	<h:outputLabel for="description" value="#{bundle.description}" styleClass="control-label"/>
                    	<h:inputTextarea id="description" label="#{bundle.description}" cols="60" rows="5" value="#{topicMBean.topic.description}" styleClass="form-control"/>
                    </div>
                    <p/>
                        <h:commandButton value="#{bundle.save}" action="#{topicMBean.save}" rendered="#{securityBackingMBean.isUserLeader}" styleClass="btn btn-primary"/>
                        <h:commandButton value="#{bundle.remove}" action="#{topicMBean.remove}" styleClass="btn btn-warning" rendered="#{securityBackingMBean.isUserLeader and topicMBean.existent}" onclick="return confirmAction('#{bundle.warnCode0005}');">
                            <f:param name="topic" value="#{topicMBean.topic.name}"/>
                        </h:commandButton>
                        <h:button value="#{bundle.cancel}" outcome="topics" styleClass="btn btn-default" style="margin-left: 5px;"/>
            </ui:define>
        </ui:composition>
    </body>
</html>

src/main/webapp/knowledge/topic_form.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!-- Yougi is a web application conceived to manage user groups or
 * communities focused on a certain domain of knowledge, whose members are
 * constantly sharing information and participating in social and educational
 * events. Copyright (C) 2011 Hildeberto Mendonça.
 *
 * This application is free software; you can redistribute it and/or modify it
 * under the terms of the GNU Lesser General Public License as published by the
 * Free Software Foundation; either version 2.1 of the License, or (at your
 * option) any later version.
 *
 * This application is distributed in the hope that it will be useful, but
 * WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
 * or FITNESS FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public
 * License for more details.
 *
 * There is a full copy of the GNU Lesser General Public License along with
 * this library. Look for the file license.txt at the root level. If you do not
 * find it, write to the Free Software Foundation, Inc., 59 Temple Place,
 * Suite 330, Boston, MA 02111-1307 USA.
 * -->
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:f="http://xmlns.jcp.org/jsf/core">
    <body>
        <ui:composition template="../layout.xhtml">
            <ui:define name="title">#{bundle.topic}</ui:define>
            <ui:define name="content">
                <h1>#{bundle.topic}</h1>
                <h:form>
                    <h:messages globalOnly="true" styleClass="alertMessage" infoClass="infoMessage" errorClass="errorMessage"/>
                    <div  class="form-group">
                    	<h:outputLabel for="name" value="#{bundle.name} *" styleClass="control-label"/>
                    	<h:inputText id="name" label="#{bundle.name}" required="true" size="20" maxlength="20" value="#{topicMBean.topic.name}" readonly="#{! empty topicMBean.topic.name}" styleClass="form-control"/>
                        <h:message for="name" errorClass="errorMessage"/>
                    </div>
                    <div class="form-group">
                        <h:outputLabel for="label" value="#{bundle.label} *" styleClass="control-label"/>
                        <h:inputText id="label" label="#{bundle.label}" required="true" size="20" maxlength="20" value="#{topicMBean.topic.label}" styleClass="form-control"/>
                        <h:message for="label" errorClass="errorMessage"/>
                    </div>
                    <div class="form-group">
                        <h:selectBooleanCheckbox id="valid" label="#{bundle.valid}" value="#{topicMBean.topic.valid}"/>
                        <h:outputLabel for="valid" value="#{bundle.valid}"/>
                    </div>
                    <div class="form-group">
                    	<h:outputLabel for="description" value="#{bundle.description}" styleClass="control-label"/>
                    	<h:inputTextarea id="description" label="#{bundle.description}" cols="60" rows="5" value="#{topicMBean.topic.description}" styleClass="form-control"/>
                    </div>
                    <p/>
                        <h:commandButton value="#{bundle.save}" action="#{topicMBean.save}" rendered="#{securityBackingMBean.isUserLeader}" styleClass="btn btn-primary"/>
                        <h:commandButton value="#{bundle.remove}" action="#{topicMBean.remove}" styleClass="btn btn-warning" rendered="#{securityBackingMBean.isUserLeader and topicMBean.existent}" onclick="return confirmAction('#{bundle.warnCode0005}');">
                            <f:param name="topic" value="#{topicMBean.topic.name}"/>
                        </h:commandButton>
                        <h:button value="#{bundle.cancel}" outcome="topics" styleClass="btn btn-default" style="margin-left: 5px;"/>
                </h:form>
            </ui:define>
        </ui:composition>
    </body>
</html>